apiVersion: v1
kind: Service
metadata:
  name: llmops-service
spec:
  selector:
    app: topic-challenger-app
  ports:
    - port: 80
      targetPort: 8501  # default port for Streamlit
  type: NodePort